
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Dec 29 2023 12:53:34 IST (Dec 29 2023 07:23:34 UTC)

// Verification Directory fv/vedic8x8 

module vedic8x8(a, b, clk, result);
  input [7:0] a, b;
  input clk;
  output [15:0] result;
  wire [7:0] a, b;
  wire clk;
  wire [15:0] result;
  wire [7:0] t7;
  wire [7:0] t6;
  wire [9:0] t5;
  wire [9:0] t4;
  wire [7:0] t3;
  wire [7:0] t2;
  wire [7:0] t1;
  wire [3:0] M1_t7;
  wire [3:0] M3_t7;
  wire [3:0] M2_t7;
  wire [3:0] M4_t7;
  wire [3:0] M4_t6;
  wire [5:0] M4_t5;
  wire [3:0] M2_t6;
  wire [5:0] M2_t5;
  wire [3:0] M3_t6;
  wire [5:0] M3_t5;
  wire [3:0] M1_t6;
  wire [5:0] M1_t5;
  wire [5:0] M3_t4;
  wire [5:0] M2_t4;
  wire [5:0] M1_t4;
  wire [5:0] M4_t4;
  wire [3:0] M3_t3;
  wire [3:0] M3_t2;
  wire [3:0] M4_t3;
  wire [3:0] M4_t2;
  wire [3:0] M1_t3;
  wire [3:0] M1_t2;
  wire [3:0] M2_t3;
  wire [3:0] M2_t2;
  wire [3:0] M2_t1;
  wire [3:0] M3_t1;
  wire [3:0] M4_t1;
  wire [3:0] M1_t1;
  wire [3:0] M4_V4_w;
  wire [3:0] M2_V2_w;
  wire [3:0] M3_V3_w;
  wire [3:0] M3_V1_w;
  wire [3:0] M1_V3_w;
  wire [3:0] M2_V4_w;
  wire [3:0] M3_V2_w;
  wire [3:0] M1_V2_w;
  wire [3:0] M4_V3_w;
  wire [3:0] M4_V1_w;
  wire [3:0] M2_V1_w;
  wire [3:0] M4_V2_w;
  wire [3:0] M2_V3_w;
  wire [3:0] M1_V1_w;
  wire [3:0] M1_V4_w;
  wire [3:0] M3_V4_w;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_241, n_242, n_243, n_244, n_245, n_246, n_247;
  wire n_248, n_249, n_250, n_251, n_252, n_253, n_254, n_255;
  wire n_256, n_257, n_258, n_259, n_260, n_261, n_262, n_263;
  wire n_264, n_265, n_266, n_267, n_268, n_269, n_270, n_271;
  wire n_273, n_274, n_275, n_276, n_277, n_278, n_279, n_280;
  wire n_281, n_282, n_283, n_284, n_285, n_286, n_287, n_288;
  wire n_289, n_290, n_291, n_292, n_293, n_294, n_295, n_296;
  wire n_297, n_298, n_299, n_300, n_301, n_302, n_303, n_304;
  wire n_305, n_306, n_307, n_308, n_309, n_310, n_311, n_312;
  wire n_313, n_314, n_315, n_316, n_317;
  DFFQX2 \op_reg[15] (.CK (clk), .D (t7[7]), .Q (result[15]));
  DFFQX2 \op_reg[14] (.CK (clk), .D (t7[6]), .Q (result[14]));
  SDFFQX1 \A3_sum_reg[7] (.CK (clk), .D (n_315), .SI (n_316), .SE
       (t6[7]), .Q (t7[7]));
  DFFQX1 \A3_sum_reg[6] (.CK (clk), .D (n_317), .Q (t7[6]));
  OA21XL g5415__2398(.A0 (t6[6]), .A1 (n_314), .B0 (n_316), .Y (n_317));
  DFFQX2 \op_reg[13] (.CK (clk), .D (t7[5]), .Q (result[13]));
  CLKINVX1 g5413(.A (n_316), .Y (n_315));
  DFFQX1 \A3_sum_reg[5] (.CK (clk), .D (n_313), .Q (t7[5]));
  NAND2XL g5417__5107(.A (t6[6]), .B (n_314), .Y (n_316));
  ADDFX1 g5418__6260(.A (t5[9]), .B (t6[5]), .CI (n_311), .CO (n_314),
       .S (n_313));
  DFFQX2 \op_reg[12] (.CK (clk), .D (t7[4]), .Q (result[12]));
  DFFQX1 \A3_sum_reg[4] (.CK (clk), .D (n_312), .Q (t7[4]));
  ADDFX1 g5421__4319(.A (t5[8]), .B (t6[4]), .CI (n_309), .CO (n_311),
       .S (n_312));
  DFFQX2 \op_reg[11] (.CK (clk), .D (t7[3]), .Q (result[11]));
  DFFQX1 \A3_sum_reg[3] (.CK (clk), .D (n_310), .Q (t7[3]));
  ADDFX1 g5424__8428(.A (t5[7]), .B (t6[3]), .CI (n_307), .CO (n_309),
       .S (n_310));
  DFFQX2 \op_reg[10] (.CK (clk), .D (t7[2]), .Q (result[10]));
  DFFQX1 \A3_sum_reg[2] (.CK (clk), .D (n_308), .Q (t7[2]));
  DFFQX2 \op_reg[9] (.CK (clk), .D (t7[1]), .Q (result[9]));
  OAI21XL g5431__5526(.A0 (n_304), .A1 (n_305), .B0 (n_306), .Y
       (n_308));
  DFFQX1 \A3_sum_reg[1] (.CK (clk), .D (n_303), .Q (t7[1]));
  OAI21X1 g5432__6783(.A0 (n_298), .A1 (n_302), .B0 (n_297), .Y
       (n_307));
  NAND2XL g5435__3680(.A (n_305), .B (n_304), .Y (n_306));
  OAI21XL g5441__1617(.A0 (n_299), .A1 (n_300), .B0 (n_301), .Y
       (n_303));
  DFFQX1 \A2_sum_reg[8] (.CK (clk), .D (n_296), .Q (t5[8]));
  DFFQX1 \A2_sum_reg[9] (.CK (clk), .D (n_295), .Q (t5[9]));
  CLKINVX1 g5436(.A (n_304), .Y (n_302));
  NAND2XL g5444__2802(.A (n_300), .B (n_299), .Y (n_301));
  DFFQX2 \op_reg[8] (.CK (clk), .D (t7[0]), .Q (result[8]));
  NAND2BXL g5437__1705(.AN (n_298), .B (n_297), .Y (n_305));
  OAI21X1 g5445__5122(.A0 (n_300), .A1 (n_293), .B0 (n_294), .Y
       (n_304));
  ADDHXL g5429__8246(.A (t4[8]), .B (n_290), .CO (n_295), .S (n_296));
  DFFQX1 \A3_sum_reg[0] (.CK (clk), .D (n_292), .Q (t7[0]));
  NOR2BX1 g5447__7098(.AN (n_294), .B (n_293), .Y (n_299));
  DFFQXL \A2_sum_reg[7] (.CK (clk), .D (n_291), .Q (t5[7]));
  NOR2XL g5439__6131(.A (t6[2]), .B (t5[6]), .Y (n_298));
  NAND2XL g5438__1881(.A (t6[2]), .B (t5[6]), .Y (n_297));
  NAND2XL g5449__5115(.A (t6[1]), .B (t5[5]), .Y (n_294));
  NOR2XL g5451__7482(.A (t6[1]), .B (t5[5]), .Y (n_293));
  OA21XL g5454__4733(.A0 (t6[0]), .A1 (t5[4]), .B0 (n_300), .Y (n_292));
  AOI21XL g5440__6161(.A0 (n_287), .A1 (n_288), .B0 (n_290), .Y
       (n_291));
  DFFQX1 \A2_sum_reg[6] (.CK (clk), .D (n_289), .Q (t5[6]));
  OA21XL g5450__9315(.A0 (t4[6]), .A1 (n_286), .B0 (n_288), .Y (n_289));
  DFFQX1 \A2_sum_reg[5] (.CK (clk), .D (n_285), .Q (t5[5]));
  NOR2XL g5443__9945(.A (n_287), .B (n_288), .Y (n_290));
  NAND2XL g5455__2883(.A (t6[0]), .B (t5[4]), .Y (n_300));
  NAND2XL g5453__2346(.A (t4[6]), .B (n_286), .Y (n_288));
  AOI21XL g5456__1666(.A0 (n_282), .A1 (n_283), .B0 (n_286), .Y
       (n_285));
  DFFQX1 \A2_sum_reg[4] (.CK (clk), .D (n_284), .Q (t5[4]));
  OA21XL g5460__7410(.A0 (t4[4]), .A1 (n_281), .B0 (n_283), .Y (n_284));
  NOR2XL g5458__6417(.A (n_282), .B (n_283), .Y (n_286));
  DFFQX2 \op_reg[7] (.CK (clk), .D (t5[3]), .Q (result[7]));
  CLKINVX1 g5461(.A (t4[7]), .Y (n_287));
  DFFQX1 \A1_sum_reg[7] (.CK (clk), .D (n_280), .Q (t4[7]));
  DFFQX1 \A1_sum_reg[8] (.CK (clk), .D (n_279), .Q (t4[8]));
  DFFQX1 \A2_sum_reg[3] (.CK (clk), .D (n_278), .Q (t5[3]));
  NAND2XL g5465__5477(.A (t4[4]), .B (n_281), .Y (n_283));
  ADDFXL g5467__2398(.A (t3[7]), .B (t2[7]), .CI (n_275), .CO (n_279),
       .S (n_280));
  DFFQX2 \op_reg[6] (.CK (clk), .D (t5[2]), .Q (result[6]));
  ADDFX1 g5466__5107(.A (t1[7]), .B (t4[3]), .CI (n_271), .CO (n_281),
       .S (n_278));
  DFFQX1 \A2_sum_reg[2] (.CK (clk), .D (n_277), .Q (t5[2]));
  DFFQX1 \A1_sum_reg[6] (.CK (clk), .D (n_276), .Q (t4[6]));
  OAI21XL g5473__6260(.A0 (n_259), .A1 (n_273), .B0 (n_274), .Y
       (n_277));
  ADDFX1 g5471__4319(.A (t2[6]), .B (t3[6]), .CI (n_258), .CO (n_275),
       .S (n_276));
  DFFQX2 \op_reg[5] (.CK (clk), .D (t5[1]), .Q (result[5]));
  NAND2XL g5477__8428(.A (n_273), .B (n_259), .Y (n_274));
  OAI21X1 g5474__5526(.A0 (n_270), .A1 (n_266), .B0 (n_269), .Y
       (n_271));
  CLKINVX1 g5476(.A (t4[5]), .Y (n_282));
  DFFQX1 \A2_sum_reg[1] (.CK (clk), .D (n_268), .Q (t5[1]));
  DFFQX1 \A1_sum_reg[5] (.CK (clk), .D (n_267), .Q (t4[5]));
  NAND2BXL g5485__6783(.AN (n_270), .B (n_269), .Y (n_273));
  DFFQX1 \M1_op_reg[7] (.CK (clk), .D (M1_t7[3]), .Q (t1[7]));
  DFFQX1 \M3_op_reg[7] (.CK (clk), .D (M3_t7[3]), .Q (t3[7]));
  DFFQX1 \M2_op_reg[7] (.CK (clk), .D (M2_t7[3]), .Q (t2[7]));
  DFFQX1 \M4_op_reg[7] (.CK (clk), .D (M4_t7[3]), .Q (t6[7]));
  OAI21XL g5490__3680(.A0 (n_263), .A1 (n_264), .B0 (n_265), .Y
       (n_268));
  OAI21XL g5491__1617(.A0 (n_260), .A1 (n_261), .B0 (n_262), .Y
       (n_267));
  NAND2XL g5492__2802(.A (t4[2]), .B (t1[6]), .Y (n_269));
  NOR2XL g5493__1705(.A (t4[2]), .B (t1[6]), .Y (n_270));
  SDFFQX1 \M4_A3_sum_reg[3] (.CK (clk), .D (n_252), .SI (n_253), .SE
       (n_236), .Q (M4_t7[3]));
  SDFFQX1 \M1_A3_sum_reg[3] (.CK (clk), .D (n_246), .SI (n_247), .SE
       (n_234), .Q (M1_t7[3]));
  SDFFQX1 \M3_A3_sum_reg[3] (.CK (clk), .D (n_248), .SI (n_249), .SE
       (n_235), .Q (M3_t7[3]));
  SDFFQX1 \M2_A3_sum_reg[3] (.CK (clk), .D (n_250), .SI (n_251), .SE
       (n_233), .Q (M2_t7[3]));
  DFFQX1 \M3_op_reg[6] (.CK (clk), .D (M3_t7[2]), .Q (t3[6]));
  DFFQX1 \M2_op_reg[6] (.CK (clk), .D (M2_t7[2]), .Q (t2[6]));
  DFFQX1 \M1_op_reg[6] (.CK (clk), .D (M1_t7[2]), .Q (t1[6]));
  NAND2XL g5499__5122(.A (n_264), .B (n_263), .Y (n_265));
  NAND2XL g5498__8246(.A (n_261), .B (n_260), .Y (n_262));
  CLKINVX1 g5480(.A (n_259), .Y (n_266));
  DFFQX1 \M4_op_reg[6] (.CK (clk), .D (M4_t7[2]), .Q (t6[6]));
  OAI21X1 g5500__7098(.A0 (n_264), .A1 (n_254), .B0 (n_255), .Y
       (n_259));
  OAI21X1 g5501__6131(.A0 (n_257), .A1 (n_240), .B0 (n_256), .Y
       (n_258));
  DFFQX1 \M3_A3_sum_reg[2] (.CK (clk), .D (n_243), .Q (M3_t7[2]));
  DFFQX1 \M1_A3_sum_reg[2] (.CK (clk), .D (n_242), .Q (M1_t7[2]));
  DFFQX1 \M4_A3_sum_reg[2] (.CK (clk), .D (n_245), .Q (M4_t7[2]));
  DFFQX1 \M2_A3_sum_reg[2] (.CK (clk), .D (n_244), .Q (M2_t7[2]));
  NAND2BXL g5507__1881(.AN (n_257), .B (n_256), .Y (n_261));
  NOR2BX1 g5506__5115(.AN (n_255), .B (n_254), .Y (n_263));
  INVXL g5508(.A (n_252), .Y (n_253));
  INVXL g5509(.A (n_250), .Y (n_251));
  INVXL g5510(.A (n_248), .Y (n_249));
  INVXL g5511(.A (n_246), .Y (n_247));
  DFFQX1 \A1_sum_reg[4] (.CK (clk), .D (n_241), .Q (t4[4]));
  ADDFXL g5512__7482(.A (M4_t6[2]), .B (M4_t5[4]), .CI (n_226), .CO
       (n_252), .S (n_245));
  ADDFXL g5513__4733(.A (M2_t6[2]), .B (M2_t5[4]), .CI (n_224), .CO
       (n_250), .S (n_244));
  ADDFXL g5514__6161(.A (M3_t6[2]), .B (M3_t5[4]), .CI (n_228), .CO
       (n_248), .S (n_243));
  ADDFXL g5515__9315(.A (M1_t6[2]), .B (M1_t5[4]), .CI (n_222), .CO
       (n_246), .S (n_242));
  NOR2XL g5517__9945(.A (t4[1]), .B (t1[5]), .Y (n_254));
  NAND2XL g5518__2883(.A (t3[5]), .B (t2[5]), .Y (n_256));
  NOR2XL g5519__2346(.A (t3[5]), .B (t2[5]), .Y (n_257));
  NAND2XL g5520__1666(.A (t4[1]), .B (t1[5]), .Y (n_255));
  OAI21XL g5532__7410(.A0 (n_237), .A1 (n_238), .B0 (n_239), .Y
       (n_241));
  DFFQX2 \op_reg[4] (.CK (clk), .D (t5[0]), .Q (result[4]));
  DFFQX1 \M1_op_reg[5] (.CK (clk), .D (M1_t7[1]), .Q (t1[5]));
  DFFQX1 \M3_op_reg[5] (.CK (clk), .D (M3_t7[1]), .Q (t3[5]));
  DFFQX1 \M4_op_reg[5] (.CK (clk), .D (M4_t7[1]), .Q (t6[5]));
  DFFQX1 \M2_op_reg[5] (.CK (clk), .D (M2_t7[1]), .Q (t2[5]));
  CLKINVX1 g5521(.A (n_260), .Y (n_240));
  DFFQX1 \A2_sum_reg[0] (.CK (clk), .D (n_230), .Q (t5[0]));
  NAND2XL g5537__6417(.A (n_238), .B (n_237), .Y (n_239));
  DFFQX1 \M4_A3_sum_reg[1] (.CK (clk), .D (n_227), .Q (M4_t7[1]));
  DFFQX1 \M1_A3_sum_reg[1] (.CK (clk), .D (n_223), .Q (M1_t7[1]));
  DFFQX1 \M3_A3_sum_reg[1] (.CK (clk), .D (n_229), .Q (M3_t7[1]));
  DFFQX1 \M2_A3_sum_reg[1] (.CK (clk), .D (n_225), .Q (M2_t7[1]));
  AOI21X1 g5540__5477(.A0 (M4_t6[3]), .A1 (M4_t5[5]), .B0 (n_221), .Y
       (n_236));
  AOI21X1 g5539__2398(.A0 (M3_t6[3]), .A1 (M3_t5[5]), .B0 (n_219), .Y
       (n_235));
  AOI21X1 g5538__5107(.A0 (M1_t6[3]), .A1 (M1_t5[5]), .B0 (n_218), .Y
       (n_234));
  AOI21X1 g5541__6260(.A0 (M2_t6[3]), .A1 (M2_t5[5]), .B0 (n_220), .Y
       (n_233));
  OAI21X1 g5542__4319(.A0 (n_232), .A1 (n_181), .B0 (n_231), .Y
       (n_260));
  NAND2BXL g5545__8428(.AN (n_232), .B (n_231), .Y (n_238));
  OA21XL g5548__5526(.A0 (t4[0]), .A1 (t1[4]), .B0 (n_264), .Y (n_230));
  ADDFX1 g5533__6783(.A (M3_t5[3]), .B (M3_t6[1]), .CI (n_200), .CO
       (n_228), .S (n_229));
  ADDFX1 g5534__3680(.A (M4_t5[3]), .B (M4_t6[1]), .CI (n_196), .CO
       (n_226), .S (n_227));
  ADDFX1 g5535__1617(.A (M2_t5[3]), .B (M2_t6[1]), .CI (n_194), .CO
       (n_224), .S (n_225));
  ADDFX1 g5536__2802(.A (M1_t5[3]), .B (M1_t6[1]), .CI (n_198), .CO
       (n_222), .S (n_223));
  NOR2XL g5546__1705(.A (M4_t6[3]), .B (M4_t5[5]), .Y (n_221));
  NOR2XL g5547__5122(.A (M2_t6[3]), .B (M2_t5[5]), .Y (n_220));
  NOR2XL g5543__8246(.A (M3_t6[3]), .B (M3_t5[5]), .Y (n_219));
  NOR2XL g5544__7098(.A (M1_t6[3]), .B (M1_t5[5]), .Y (n_218));
  NAND2XL g5557__6131(.A (t3[4]), .B (t2[4]), .Y (n_231));
  NOR2XL g5558__1881(.A (t3[4]), .B (t2[4]), .Y (n_232));
  NAND2XL g5559__5115(.A (t4[0]), .B (t1[4]), .Y (n_264));
  DFFQX1 \M3_A2_sum_reg[4] (.CK (clk), .D (n_217), .Q (M3_t5[4]));
  DFFQX1 \M1_A2_sum_reg[4] (.CK (clk), .D (n_213), .Q (M1_t5[4]));
  DFFQX1 \M1_A2_sum_reg[5] (.CK (clk), .D (n_212), .Q (M1_t5[5]));
  DFFQX1 \M3_A2_sum_reg[5] (.CK (clk), .D (n_216), .Q (M3_t5[5]));
  DFFQX1 \M2_A2_sum_reg[4] (.CK (clk), .D (n_215), .Q (M2_t5[4]));
  DFFQX1 \M4_A2_sum_reg[4] (.CK (clk), .D (n_211), .Q (M4_t5[4]));
  DFFQX1 \M2_A2_sum_reg[5] (.CK (clk), .D (n_214), .Q (M2_t5[5]));
  DFFQX1 \M4_A2_sum_reg[5] (.CK (clk), .D (n_210), .Q (M4_t5[5]));
  DFFQX1 \M3_op_reg[4] (.CK (clk), .D (M3_t7[0]), .Q (t3[4]));
  DFFQX1 \M2_op_reg[4] (.CK (clk), .D (M2_t7[0]), .Q (t2[4]));
  DFFQX1 \M4_op_reg[4] (.CK (clk), .D (M4_t7[0]), .Q (t6[4]));
  DFFQX1 \M1_op_reg[4] (.CK (clk), .D (M1_t7[0]), .Q (t1[4]));
  ADDHXL g5560__7482(.A (M3_t4[4]), .B (n_206), .CO (n_216), .S
       (n_217));
  ADDHXL g5561__4733(.A (M2_t4[4]), .B (n_202), .CO (n_214), .S
       (n_215));
  ADDHXL g5562__6161(.A (M1_t4[4]), .B (n_204), .CO (n_212), .S
       (n_213));
  ADDHXL g5563__9315(.A (M4_t4[4]), .B (n_208), .CO (n_210), .S
       (n_211));
  DFFQX1 \M3_A2_sum_reg[3] (.CK (clk), .D (n_207), .Q (M3_t5[3]));
  DFFQX1 \M1_A2_sum_reg[3] (.CK (clk), .D (n_205), .Q (M1_t5[3]));
  DFFQX1 \M4_A2_sum_reg[3] (.CK (clk), .D (n_209), .Q (M4_t5[3]));
  DFFQX1 \M2_A2_sum_reg[3] (.CK (clk), .D (n_203), .Q (M2_t5[3]));
  DFFQX1 \M3_A3_sum_reg[0] (.CK (clk), .D (n_201), .Q (M3_t7[0]));
  DFFQX1 \M1_A3_sum_reg[0] (.CK (clk), .D (n_199), .Q (M1_t7[0]));
  DFFQX1 \M4_A3_sum_reg[0] (.CK (clk), .D (n_197), .Q (M4_t7[0]));
  DFFQX1 \M2_A3_sum_reg[0] (.CK (clk), .D (n_195), .Q (M2_t7[0]));
  DFFQX1 \A1_sum_reg[3] (.CK (clk), .D (n_193), .Q (t4[3]));
  AOI21XL g5588__9945(.A0 (n_192), .A1 (n_191), .B0 (n_208), .Y
       (n_209));
  AOI21XL g5589__2883(.A0 (n_188), .A1 (n_187), .B0 (n_206), .Y
       (n_207));
  AOI21XL g5590__2346(.A0 (n_186), .A1 (n_185), .B0 (n_204), .Y
       (n_205));
  AOI21XL g5591__1666(.A0 (n_190), .A1 (n_189), .B0 (n_202), .Y
       (n_203));
  AOI2BB1X1 g5578__7410(.A0N (M3_t6[0]), .A1N (M3_t5[2]), .B0 (n_200),
       .Y (n_201));
  AOI2BB1X1 g5579__6417(.A0N (M1_t6[0]), .A1N (M1_t5[2]), .B0 (n_198),
       .Y (n_199));
  AOI2BB1X1 g5580__5477(.A0N (M4_t6[0]), .A1N (M4_t5[2]), .B0 (n_196),
       .Y (n_197));
  AOI2BB1X1 g5581__2398(.A0N (M2_t6[0]), .A1N (M2_t5[2]), .B0 (n_194),
       .Y (n_195));
  OAI21XL g5582__5107(.A0 (n_182), .A1 (n_183), .B0 (n_184), .Y
       (n_193));
  NOR2XL g5599__6260(.A (n_192), .B (n_191), .Y (n_208));
  NOR2XL g5600__4319(.A (n_190), .B (n_189), .Y (n_202));
  NOR2XL g5601__8428(.A (n_188), .B (n_187), .Y (n_206));
  NOR2XL g5602__5526(.A (n_186), .B (n_185), .Y (n_204));
  NAND2XL g5583__6783(.A (n_183), .B (n_182), .Y (n_184));
  CLKINVX1 g5573(.A (n_181), .Y (n_237));
  AND2X1 g5584__3680(.A (M4_t5[2]), .B (M4_t6[0]), .Y (n_196));
  AND2X1 g5587__1617(.A (M3_t5[2]), .B (M3_t6[0]), .Y (n_200));
  AND2X1 g5586__2802(.A (M2_t5[2]), .B (M2_t6[0]), .Y (n_194));
  AND2X1 g5585__1705(.A (M1_t5[2]), .B (M1_t6[0]), .Y (n_198));
  DFFQX1 \A1_sum_reg[2] (.CK (clk), .D (n_179), .Q (t4[2]));
  AOI21X1 g5592__5122(.A0 (n_180), .A1 (n_182), .B0 (n_178), .Y
       (n_181));
  CLKINVX1 g5607(.A (M1_t4[3]), .Y (n_186));
  CLKINVX1 g5608(.A (M3_t4[3]), .Y (n_188));
  CLKINVX1 g5609(.A (M4_t4[3]), .Y (n_192));
  CLKINVX1 g5618(.A (M2_t4[3]), .Y (n_190));
  DFFQX1 \M1_A1_sum_reg[4] (.CK (clk), .D (n_171), .Q (M1_t4[4]));
  DFFQX1 \M1_A1_sum_reg[3] (.CK (clk), .D (n_172), .Q (M1_t4[3]));
  DFFQX1 \M3_A2_sum_reg[2] (.CK (clk), .D (n_162), .Q (M3_t5[2]));
  NAND2XL g5598__8246(.A (n_177), .B (n_180), .Y (n_183));
  DFFQX1 \M2_A2_sum_reg[2] (.CK (clk), .D (n_168), .Q (M2_t5[2]));
  DFFQX1 \M1_A2_sum_reg[2] (.CK (clk), .D (n_163), .Q (M1_t5[2]));
  DFFQX1 \M4_A2_sum_reg[2] (.CK (clk), .D (n_167), .Q (M4_t5[2]));
  DFFQX1 \M2_A1_sum_reg[4] (.CK (clk), .D (n_169), .Q (M2_t4[4]));
  DFFQX1 \M3_A1_sum_reg[3] (.CK (clk), .D (n_176), .Q (M3_t4[3]));
  DFFQX1 \M4_A1_sum_reg[3] (.CK (clk), .D (n_174), .Q (M4_t4[3]));
  OAI21XL g5619__7098(.A0 (n_164), .A1 (n_165), .B0 (n_166), .Y
       (n_179));
  DFFQX1 \M4_A1_sum_reg[4] (.CK (clk), .D (n_173), .Q (M4_t4[4]));
  DFFQX1 \M2_A1_sum_reg[3] (.CK (clk), .D (n_170), .Q (M2_t4[3]));
  DFFQX1 \M3_A1_sum_reg[4] (.CK (clk), .D (n_175), .Q (M3_t4[4]));
  CLKINVX1 g5604(.A (n_177), .Y (n_178));
  ADDFXL g5628__6131(.A (M3_t3[3]), .B (M3_t2[3]), .CI (n_148), .CO
       (n_175), .S (n_176));
  ADDFXL g5629__1881(.A (M4_t3[3]), .B (M4_t2[3]), .CI (n_146), .CO
       (n_173), .S (n_174));
  ADDFXL g5630__5115(.A (M1_t3[3]), .B (M1_t2[3]), .CI (n_144), .CO
       (n_171), .S (n_172));
  ADDFXL g5631__7482(.A (M2_t3[3]), .B (M2_t2[3]), .CI (n_154), .CO
       (n_169), .S (n_170));
  OA21XL g5620__4733(.A0 (M2_t4[2]), .A1 (n_159), .B0 (n_189), .Y
       (n_168));
  OA21XL g5621__6161(.A0 (M4_t4[2]), .A1 (n_158), .B0 (n_191), .Y
       (n_167));
  NAND2XL g5605__9315(.A (t3[3]), .B (t2[3]), .Y (n_177));
  OR2XL g5606__9945(.A (t3[3]), .B (t2[3]), .Y (n_180));
  NAND2XL g5637__2883(.A (n_165), .B (n_164), .Y (n_166));
  OA21XL g5623__2346(.A0 (M1_t4[2]), .A1 (n_156), .B0 (n_185), .Y
       (n_163));
  OA21XL g5622__1666(.A0 (M3_t4[2]), .A1 (n_157), .B0 (n_187), .Y
       (n_162));
  DFFQX2 \op_reg[3] (.CK (clk), .D (t1[3]), .Q (result[3]));
  OAI21X1 g5638__7410(.A0 (n_161), .A1 (n_139), .B0 (n_160), .Y
       (n_182));
  DFFQX1 \M1_op_reg[3] (.CK (clk), .D (M1_t5[1]), .Q (t1[3]));
  DFFQX1 \M4_op_reg[3] (.CK (clk), .D (M4_t5[1]), .Q (t6[3]));
  DFFQX1 \M3_op_reg[3] (.CK (clk), .D (M3_t5[1]), .Q (t3[3]));
  DFFQX1 \M2_op_reg[3] (.CK (clk), .D (M2_t5[1]), .Q (t2[3]));
  NAND2BXL g5646__6417(.AN (n_161), .B (n_160), .Y (n_165));
  NAND2XL g5639__5477(.A (M2_t4[2]), .B (n_159), .Y (n_189));
  NAND2XL g5636__2398(.A (M4_t4[2]), .B (n_158), .Y (n_191));
  NAND2XL g5641__5107(.A (M3_t4[2]), .B (n_157), .Y (n_187));
  NAND2XL g5640__6260(.A (M1_t4[2]), .B (n_156), .Y (n_185));
  DFFQX1 \M1_A2_sum_reg[1] (.CK (clk), .D (n_150), .Q (M1_t5[1]));
  DFFQX1 \M3_A2_sum_reg[1] (.CK (clk), .D (n_152), .Q (M3_t5[1]));
  DFFQX1 \M4_A2_sum_reg[1] (.CK (clk), .D (n_151), .Q (M4_t5[1]));
  DFFQX1 \M2_A2_sum_reg[1] (.CK (clk), .D (n_153), .Q (M2_t5[1]));
  DFFQX1 \M1_A1_sum_reg[2] (.CK (clk), .D (n_145), .Q (M1_t4[2]));
  DFFQX2 \op_reg[2] (.CK (clk), .D (t1[2]), .Q (result[2]));
  DFFQX1 \M4_A1_sum_reg[2] (.CK (clk), .D (n_147), .Q (M4_t4[2]));
  NAND2XL g5651__4319(.A (t3[2]), .B (t2[2]), .Y (n_160));
  DFFQX1 \M2_A1_sum_reg[2] (.CK (clk), .D (n_155), .Q (M2_t4[2]));
  NOR2XL g5653__8428(.A (t3[2]), .B (t2[2]), .Y (n_161));
  DFFQX1 \M3_A1_sum_reg[2] (.CK (clk), .D (n_149), .Q (M3_t4[2]));
  ADDFX1 g5657__5526(.A (M2_t2[2]), .B (M2_t3[2]), .CI (n_123), .CO
       (n_154), .S (n_155));
  ADDFX1 g5642__6783(.A (M2_t4[1]), .B (M2_t1[3]), .CI (n_131), .CO
       (n_159), .S (n_153));
  ADDFX1 g5643__3680(.A (M3_t4[1]), .B (M3_t1[3]), .CI (n_133), .CO
       (n_157), .S (n_152));
  ADDFX1 g5644__1617(.A (M4_t4[1]), .B (M4_t1[3]), .CI (n_135), .CO
       (n_158), .S (n_151));
  ADDFX1 g5645__2802(.A (M1_t4[1]), .B (M1_t1[3]), .CI (n_137), .CO
       (n_156), .S (n_150));
  ADDFX1 g5654__1705(.A (M3_t2[2]), .B (M3_t3[2]), .CI (n_129), .CO
       (n_148), .S (n_149));
  ADDFX1 g5655__5122(.A (M4_t2[2]), .B (M4_t3[2]), .CI (n_127), .CO
       (n_146), .S (n_147));
  ADDFX1 g5656__8246(.A (M1_t2[2]), .B (M1_t3[2]), .CI (n_125), .CO
       (n_144), .S (n_145));
  DFFQX1 \M1_op_reg[2] (.CK (clk), .D (M1_t5[0]), .Q (t1[2]));
  DFFQX1 \A1_sum_reg[1] (.CK (clk), .D (n_143), .Q (t4[1]));
  DFFQX1 \M4_op_reg[2] (.CK (clk), .D (M4_t5[0]), .Q (t6[2]));
  DFFQX1 \M3_op_reg[2] (.CK (clk), .D (M3_t5[0]), .Q (t3[2]));
  DFFQX1 \M2_op_reg[2] (.CK (clk), .D (M2_t5[0]), .Q (t2[2]));
  OAI21XL g5682__7098(.A0 (n_140), .A1 (n_141), .B0 (n_142), .Y
       (n_143));
  DFFQX1 \M2_A2_sum_reg[0] (.CK (clk), .D (n_132), .Q (M2_t5[0]));
  DFFQX1 \M1_A2_sum_reg[0] (.CK (clk), .D (n_138), .Q (M1_t5[0]));
  DFFQX1 \M4_A2_sum_reg[0] (.CK (clk), .D (n_136), .Q (M4_t5[0]));
  DFFQX1 \M3_A2_sum_reg[0] (.CK (clk), .D (n_134), .Q (M3_t5[0]));
  DFFQX1 \M1_A1_sum_reg[1] (.CK (clk), .D (n_126), .Q (M1_t4[1]));
  NAND2XL g5702__6131(.A (n_141), .B (n_140), .Y (n_142));
  CLKINVX1 g5667(.A (n_164), .Y (n_139));
  DFFQX1 \M2_A1_sum_reg[1] (.CK (clk), .D (n_124), .Q (M2_t4[1]));
  DFFQX1 \M3_A1_sum_reg[1] (.CK (clk), .D (n_130), .Q (M3_t4[1]));
  AOI2BB1X1 g5673__1881(.A0N (M1_t4[0]), .A1N (M1_t1[2]), .B0 (n_137),
       .Y (n_138));
  AOI2BB1X1 g5672__5115(.A0N (M4_t4[0]), .A1N (M4_t1[2]), .B0 (n_135),
       .Y (n_136));
  DFFQX1 \M4_A1_sum_reg[1] (.CK (clk), .D (n_128), .Q (M4_t4[1]));
  AOI2BB1X1 g5674__7482(.A0N (M3_t4[0]), .A1N (M3_t1[2]), .B0 (n_133),
       .Y (n_134));
  AOI2BB1X1 g5675__4733(.A0N (M2_t4[0]), .A1N (M2_t1[2]), .B0 (n_131),
       .Y (n_132));
  OAI21X1 g5718__6161(.A0 (n_141), .A1 (n_121), .B0 (n_122), .Y
       (n_164));
  ADDFX1 g5679__9315(.A (M3_t2[1]), .B (M3_t3[1]), .CI (n_82), .CO
       (n_129), .S (n_130));
  ADDFX1 g5676__9945(.A (M4_t2[1]), .B (M4_t3[1]), .CI (n_84), .CO
       (n_127), .S (n_128));
  ADDFX1 g5677__2883(.A (M1_t2[1]), .B (M1_t3[1]), .CI (n_80), .CO
       (n_125), .S (n_126));
  ADDFX1 g5678__2346(.A (M2_t2[1]), .B (M2_t3[1]), .CI (n_86), .CO
       (n_123), .S (n_124));
  AND2X1 g5680__1666(.A (M1_t1[2]), .B (M1_t4[0]), .Y (n_137));
  AND2X1 g5681__7410(.A (M3_t1[2]), .B (M3_t4[0]), .Y (n_133));
  AND2X1 g5683__6417(.A (M2_t1[2]), .B (M2_t4[0]), .Y (n_131));
  AND2X1 g5684__5477(.A (M4_t1[2]), .B (M4_t4[0]), .Y (n_135));
  NOR2BX1 g5735__2398(.AN (n_122), .B (n_121), .Y (n_140));
  DFFQX1 M1_V3_H1_sum_reg(.CK (clk), .D (n_112), .Q (M1_t3[2]));
  DFFQX1 M1_V2_H1_sum_reg(.CK (clk), .D (n_106), .Q (M1_t2[2]));
  DFFQX1 M1_V3_H1_carry_reg(.CK (clk), .D (n_111), .Q (M1_t3[3]));
  DFFQX1 M1_V2_H1_carry_reg(.CK (clk), .D (n_105), .Q (M1_t2[3]));
  DFFQX1 M2_V3_H1_sum_reg(.CK (clk), .D (n_96), .Q (M2_t3[2]));
  DFFQX1 M3_V2_H1_carry_reg(.CK (clk), .D (n_107), .Q (M3_t2[3]));
  DFFQX1 M2_V2_H1_carry_reg(.CK (clk), .D (n_117), .Q (M2_t2[3]));
  DFFQX1 M4_V3_H1_carry_reg(.CK (clk), .D (n_103), .Q (M4_t3[3]));
  DFFQX1 M3_V4_H1_sum_reg(.CK (clk), .D (n_90), .Q (M3_t6[2]));
  DFFQX2 \op_reg[1] (.CK (clk), .D (t1[1]), .Q (result[1]));
  DFFQX1 M4_V2_H1_sum_reg(.CK (clk), .D (n_98), .Q (M4_t2[2]));
  DFFQX1 M4_V4_H1_sum_reg(.CK (clk), .D (n_120), .Q (M4_t6[2]));
  DFFQX1 M1_V4_H1_carry_reg(.CK (clk), .D (n_91), .Q (M1_t6[3]));
  DFFQX1 M4_V4_H1_carry_reg(.CK (clk), .D (n_119), .Q (M4_t6[3]));
  DFFQX1 M3_V4_H1_carry_reg(.CK (clk), .D (n_89), .Q (M3_t6[3]));
  DFFQX1 M4_V1_H1_sum_reg(.CK (clk), .D (n_102), .Q (M4_t1[2]));
  DFFQX1 M1_V1_H1_sum_reg(.CK (clk), .D (n_94), .Q (M1_t1[2]));
  DFFQX1 M2_V1_H1_carry_reg(.CK (clk), .D (n_99), .Q (M2_t1[3]));
  DFFQX1 M3_V2_H1_sum_reg(.CK (clk), .D (n_108), .Q (M3_t2[2]));
  DFFQX1 M3_V3_H1_sum_reg(.CK (clk), .D (n_116), .Q (M3_t3[2]));
  DFFQX1 M3_V3_H1_carry_reg(.CK (clk), .D (n_115), .Q (M3_t3[3]));
  DFFQX1 M2_V4_H1_sum_reg(.CK (clk), .D (n_110), .Q (M2_t6[2]));
  DFFQX1 M1_V1_H1_carry_reg(.CK (clk), .D (n_93), .Q (M1_t1[3]));
  DFFQX1 M4_V2_H1_carry_reg(.CK (clk), .D (n_97), .Q (M4_t2[3]));
  DFFQX1 M3_V1_H1_carry_reg(.CK (clk), .D (n_113), .Q (M3_t1[3]));
  DFFQX1 M2_V3_H1_carry_reg(.CK (clk), .D (n_95), .Q (M2_t3[3]));
  DFFQX1 M2_V2_H1_sum_reg(.CK (clk), .D (n_118), .Q (M2_t2[2]));
  DFFQX1 M4_V3_H1_sum_reg(.CK (clk), .D (n_104), .Q (M4_t3[2]));
  DFFQX1 M1_V4_H1_sum_reg(.CK (clk), .D (n_92), .Q (M1_t6[2]));
  DFFQX1 M4_V1_H1_carry_reg(.CK (clk), .D (n_101), .Q (M4_t1[3]));
  DFFQX1 M2_V1_H1_sum_reg(.CK (clk), .D (n_100), .Q (M2_t1[2]));
  NOR2XL g5739__5107(.A (t3[1]), .B (t2[1]), .Y (n_121));
  DFFQX1 M3_V1_H1_sum_reg(.CK (clk), .D (n_114), .Q (M3_t1[2]));
  NAND2XL g5738__6260(.A (t3[1]), .B (t2[1]), .Y (n_122));
  DFFQX1 M2_V4_H1_carry_reg(.CK (clk), .D (n_109), .Q (M2_t6[3]));
  DFFQX1 \A1_sum_reg[0] (.CK (clk), .D (n_88), .Q (t4[0]));
  ADDHX1 g5726__4319(.A (M4_V4_w[3]), .B (n_15), .CO (n_119), .S
       (n_120));
  ADDHX1 g5722__8428(.A (M2_V2_w[3]), .B (n_3), .CO (n_117), .S
       (n_118));
  ADDHX1 g5733__5526(.A (M3_V3_w[3]), .B (n_0), .CO (n_115), .S
       (n_116));
  ADDHX1 g5724__6783(.A (M3_V1_w[3]), .B (n_7), .CO (n_113), .S
       (n_114));
  ADDHX1 g5731__3680(.A (M1_V3_w[3]), .B (n_1), .CO (n_111), .S
       (n_112));
  ADDHX1 g5721__1617(.A (M2_V4_w[3]), .B (n_6), .CO (n_109), .S
       (n_110));
  ADDHX1 g5734__2802(.A (M3_V2_w[3]), .B (n_13), .CO (n_107), .S
       (n_108));
  ADDHX1 g5728__1705(.A (M1_V2_w[3]), .B (n_12), .CO (n_105), .S
       (n_106));
  ADDHX1 g5719__5122(.A (M4_V3_w[3]), .B (n_4), .CO (n_103), .S
       (n_104));
  ADDHX1 g5732__8246(.A (M4_V1_w[3]), .B (n_9), .CO (n_101), .S
       (n_102));
  ADDHX1 g5725__7098(.A (M2_V1_w[3]), .B (n_8), .CO (n_99), .S (n_100));
  ADDHX1 g5729__6131(.A (M4_V2_w[3]), .B (n_2), .CO (n_97), .S (n_98));
  ADDHX1 g5723__1881(.A (M2_V3_w[3]), .B (n_11), .CO (n_95), .S (n_96));
  ADDHX1 g5720__5115(.A (M1_V1_w[3]), .B (n_5), .CO (n_93), .S (n_94));
  ADDHX1 g5727__7482(.A (M1_V4_w[3]), .B (n_14), .CO (n_91), .S (n_92));
  ADDHX1 g5730__4733(.A (M3_V4_w[3]), .B (n_10), .CO (n_89), .S (n_90));
  DFFQX1 \M2_op_reg[1] (.CK (clk), .D (M2_t1[1]), .Q (t2[1]));
  DFFQX1 \M4_op_reg[1] (.CK (clk), .D (M4_t1[1]), .Q (t6[1]));
  DFFQX1 \M1_op_reg[1] (.CK (clk), .D (M1_t1[1]), .Q (t1[1]));
  DFFQX1 \M3_op_reg[1] (.CK (clk), .D (M3_t1[1]), .Q (t3[1]));
  DFFQX1 \M3_A1_sum_reg[0] (.CK (clk), .D (n_83), .Q (M3_t4[0]));
  DFFQX1 \M2_A1_sum_reg[0] (.CK (clk), .D (n_87), .Q (M2_t4[0]));
  OA21XL g5766__6161(.A0 (t3[0]), .A1 (t2[0]), .B0 (n_141), .Y (n_88));
  DFFQX1 \M1_A1_sum_reg[0] (.CK (clk), .D (n_81), .Q (M1_t4[0]));
  DFFQX1 \M4_A1_sum_reg[0] (.CK (clk), .D (n_85), .Q (M4_t4[0]));
  DFFQX1 M1_V4_H0_sum_reg(.CK (clk), .D (n_53), .Q (M1_t6[1]));
  DFFQX1 M2_V4_H0_sum_reg(.CK (clk), .D (n_70), .Q (M2_t6[1]));
  DFFQX1 M3_V3_H0_sum_reg(.CK (clk), .D (n_79), .Q (M3_t3[1]));
  DFFQX1 M3_V2_H0_sum_reg(.CK (clk), .D (n_49), .Q (M3_t2[1]));
  DFFQX1 M3_V1_H0_sum_reg(.CK (clk), .D (n_67), .Q (M3_t1[1]));
  DFFQX1 M4_V1_H0_sum_reg(.CK (clk), .D (n_74), .Q (M4_t1[1]));
  DFFQX1 M2_V1_H0_sum_reg(.CK (clk), .D (n_63), .Q (M2_t1[1]));
  DFFQX1 M3_V4_H0_sum_reg(.CK (clk), .D (n_76), .Q (M3_t6[1]));
  DFFQX1 M1_V3_H0_sum_reg(.CK (clk), .D (n_65), .Q (M1_t3[1]));
  DFFQX1 M4_V2_H0_sum_reg(.CK (clk), .D (n_78), .Q (M4_t2[1]));
  DFFQX1 M2_V3_H0_sum_reg(.CK (clk), .D (n_61), .Q (M2_t3[1]));
  DFFQX1 M2_V2_H0_sum_reg(.CK (clk), .D (n_55), .Q (M2_t2[1]));
  DFFQX1 M4_V3_H0_sum_reg(.CK (clk), .D (n_59), .Q (M4_t3[1]));
  DFFQX1 M4_V4_H0_sum_reg(.CK (clk), .D (n_57), .Q (M4_t6[1]));
  DFFQX1 M1_V2_H0_sum_reg(.CK (clk), .D (n_69), .Q (M1_t2[1]));
  DFFQX1 M1_V1_H0_sum_reg(.CK (clk), .D (n_72), .Q (M1_t1[1]));
  AOI21XL g5782__9315(.A0 (M2_t3[0]), .A1 (M2_t2[0]), .B0 (n_86), .Y
       (n_87));
  AOI21XL g5784__9945(.A0 (M4_t3[0]), .A1 (M4_t2[0]), .B0 (n_84), .Y
       (n_85));
  AOI21XL g5785__2883(.A0 (M3_t3[0]), .A1 (M3_t2[0]), .B0 (n_82), .Y
       (n_83));
  AOI21XL g5786__2346(.A0 (M1_t3[0]), .A1 (M1_t2[0]), .B0 (n_80), .Y
       (n_81));
  DFFQX2 \op_reg[0] (.CK (clk), .D (t1[0]), .Q (result[0]));
  NAND2XL g5783__1666(.A (t3[0]), .B (t2[0]), .Y (n_141));
  AOI21XL g5787__7410(.A0 (n_17), .A1 (n_16), .B0 (n_62), .Y (n_79));
  DFFQX1 M3_V4_H0_carry_reg(.CK (clk), .D (n_75), .Q (M3_V4_w[3]));
  DFFQX1 M3_V1_H0_carry_reg(.CK (clk), .D (n_66), .Q (M3_V1_w[3]));
  DFFQX1 M4_V2_H0_carry_reg(.CK (clk), .D (n_77), .Q (M4_V2_w[3]));
  DFFQX1 M1_V4_H0_carry_reg(.CK (clk), .D (n_52), .Q (M1_V4_w[3]));
  DFFQX1 M1_V1_H0_carry_reg(.CK (clk), .D (n_71), .Q (M1_V1_w[3]));
  DFFQX1 M2_V3_H0_carry_reg(.CK (clk), .D (n_60), .Q (M2_V3_w[3]));
  DFFQX1 M2_V2_H0_carry_reg(.CK (clk), .D (n_54), .Q (M2_V2_w[3]));
  AOI21XL g5802__6417(.A0 (n_27), .A1 (n_26), .B0 (n_77), .Y (n_78));
  DFFQX1 M4_V1_H0_carry_reg(.CK (clk), .D (n_73), .Q (M4_V1_w[3]));
  DFFQX1 M1_V2_H0_carry_reg(.CK (clk), .D (n_68), .Q (M1_V2_w[3]));
  DFFQX1 M4_V3_H0_carry_reg(.CK (clk), .D (n_58), .Q (M4_V3_w[3]));
  DFFQX1 M4_V4_H0_carry_reg(.CK (clk), .D (n_56), .Q (M4_V4_w[3]));
  DFFQX1 M1_V3_H0_carry_reg(.CK (clk), .D (n_64), .Q (M1_V3_w[3]));
  AOI21XL g5806__5477(.A0 (n_43), .A1 (n_42), .B0 (n_75), .Y (n_76));
  AOI21XL g5805__2398(.A0 (n_41), .A1 (n_40), .B0 (n_73), .Y (n_74));
  AOI21XL g5788__5107(.A0 (n_39), .A1 (n_38), .B0 (n_71), .Y (n_72));
  AOI21XL g5792__6260(.A0 (n_31), .A1 (n_30), .B0 (n_50), .Y (n_70));
  AOI21XL g5793__4319(.A0 (n_21), .A1 (n_20), .B0 (n_68), .Y (n_69));
  AOI21XL g5794__8428(.A0 (n_33), .A1 (n_32), .B0 (n_66), .Y (n_67));
  AOI21XL g5795__5526(.A0 (n_45), .A1 (n_44), .B0 (n_64), .Y (n_65));
  AOI21XL g5799__6783(.A0 (n_23), .A1 (n_22), .B0 (n_51), .Y (n_63));
  DFFQX1 M3_V3_H0_carry_reg(.CK (clk), .D (n_62), .Q (M3_V3_w[3]));
  AOI21XL g5801__3680(.A0 (n_19), .A1 (n_18), .B0 (n_60), .Y (n_61));
  AOI21XL g5803__1617(.A0 (n_47), .A1 (n_46), .B0 (n_58), .Y (n_59));
  AOI21XL g5804__2802(.A0 (n_35), .A1 (n_34), .B0 (n_56), .Y (n_57));
  DFFQX1 M3_V2_H0_carry_reg(.CK (clk), .D (n_48), .Q (M3_V2_w[3]));
  AOI21XL g5790__1705(.A0 (n_25), .A1 (n_24), .B0 (n_54), .Y (n_55));
  AOI21XL g5800__5122(.A0 (n_29), .A1 (n_28), .B0 (n_52), .Y (n_53));
  DFFQX1 M2_V1_H0_carry_reg(.CK (clk), .D (n_51), .Q (M2_V1_w[3]));
  DFFQX1 M2_V4_H0_carry_reg(.CK (clk), .D (n_50), .Q (M2_V4_w[3]));
  AOI21XL g5791__8246(.A0 (n_37), .A1 (n_36), .B0 (n_48), .Y (n_49));
  DFFQX1 \M1_op_reg[0] (.CK (clk), .D (M1_t1[0]), .Q (t1[0]));
  DFFQX1 \M3_op_reg[0] (.CK (clk), .D (M3_t1[0]), .Q (t3[0]));
  NOR2XL g5807__7098(.A (M4_t3[0]), .B (M4_t2[0]), .Y (n_84));
  NOR2XL g5808__6131(.A (M1_t3[0]), .B (M1_t2[0]), .Y (n_80));
  DFFQX1 \M2_op_reg[0] (.CK (clk), .D (M2_t1[0]), .Q (t2[0]));
  NOR2XL g5810__1881(.A (M2_t3[0]), .B (M2_t2[0]), .Y (n_86));
  NOR2XL g5809__5115(.A (M3_t3[0]), .B (M3_t2[0]), .Y (n_82));
  DFFQX1 \M4_op_reg[0] (.CK (clk), .D (M4_t1[0]), .Q (t6[0]));
  NOR2XL g5831__7482(.A (n_47), .B (n_46), .Y (n_58));
  NOR2XL g5830__4733(.A (n_45), .B (n_44), .Y (n_64));
  NOR2XL g5837__6161(.A (n_43), .B (n_42), .Y (n_75));
  NOR2XL g5827__9315(.A (n_41), .B (n_40), .Y (n_73));
  NOR2XL g5838__9945(.A (n_39), .B (n_38), .Y (n_71));
  NOR2XL g5832__2883(.A (n_37), .B (n_36), .Y (n_48));
  NOR2XL g5829__2346(.A (n_35), .B (n_34), .Y (n_56));
  NOR2XL g5842__1666(.A (n_33), .B (n_32), .Y (n_66));
  NOR2XL g5833__7410(.A (n_31), .B (n_30), .Y (n_50));
  NOR2XL g5836__6417(.A (n_29), .B (n_28), .Y (n_52));
  NOR2XL g5841__5477(.A (n_27), .B (n_26), .Y (n_77));
  NOR2XL g5839__2398(.A (n_25), .B (n_24), .Y (n_54));
  NOR2XL g5828__5107(.A (n_23), .B (n_22), .Y (n_51));
  NOR2XL g5835__6260(.A (n_21), .B (n_20), .Y (n_68));
  NOR2XL g5834__4319(.A (n_19), .B (n_18), .Y (n_60));
  NOR2XL g5840__8428(.A (n_17), .B (n_16), .Y (n_62));
  DFFTRXL M1_V1_res_reg(.CK (clk), .D (a[0]), .RN (b[0]), .Q
       (M1_t1[0]), .QN (UNCONNECTED));
  DFFTRXL M3_V1_res_reg(.CK (clk), .D (a[0]), .RN (b[4]), .Q
       (M3_t1[0]), .QN (UNCONNECTED0));
  DFFTRXL M1_V4_res_reg(.CK (clk), .D (a[2]), .RN (b[2]), .Q
       (M1_t6[0]), .QN (UNCONNECTED1));
  DFFTRXL M4_V3_res_reg(.CK (clk), .D (a[4]), .RN (b[6]), .Q
       (UNCONNECTED2), .QN (M4_t3[0]));
  DFFTRXL M2_V3_res_reg(.CK (clk), .D (a[4]), .RN (b[2]), .Q
       (UNCONNECTED3), .QN (M2_t3[0]));
  DFFTRXL M1_V2_res_reg(.CK (clk), .D (a[2]), .RN (b[0]), .Q
       (UNCONNECTED4), .QN (M1_t2[0]));
  DFFTRXL M3_V3_res_reg(.CK (clk), .D (a[0]), .RN (b[6]), .Q
       (UNCONNECTED5), .QN (M3_t3[0]));
  DFFTRXL M3_V4_res_reg(.CK (clk), .D (a[2]), .RN (b[6]), .Q
       (M3_t6[0]), .QN (UNCONNECTED6));
  DFFTRXL M2_V1_res_reg(.CK (clk), .D (a[4]), .RN (b[0]), .Q
       (M2_t1[0]), .QN (UNCONNECTED7));
  DFFTRXL M4_V1_res_reg(.CK (clk), .D (a[4]), .RN (b[4]), .Q
       (M4_t1[0]), .QN (UNCONNECTED8));
  DFFTRXL M4_V4_res_reg(.CK (clk), .D (a[6]), .RN (b[6]), .Q
       (M4_t6[0]), .QN (UNCONNECTED9));
  DFFTRXL M2_V2_res_reg(.CK (clk), .D (a[6]), .RN (b[0]), .Q
       (UNCONNECTED10), .QN (M2_t2[0]));
  DFFTRXL M2_V4_res_reg(.CK (clk), .D (a[6]), .RN (b[2]), .Q
       (M2_t6[0]), .QN (UNCONNECTED11));
  DFFTRXL M4_V2_res_reg(.CK (clk), .D (a[6]), .RN (b[4]), .Q
       (UNCONNECTED12), .QN (M4_t2[0]));
  DFFTRXL M3_V2_res_reg(.CK (clk), .D (a[2]), .RN (b[4]), .Q
       (UNCONNECTED13), .QN (M3_t2[0]));
  DFFTRXL M1_V3_res_reg(.CK (clk), .D (a[0]), .RN (b[2]), .Q
       (UNCONNECTED14), .QN (M1_t3[0]));
  AND2X1 g5886__5526(.A (b[7]), .B (a[7]), .Y (n_15));
  AND2X1 g5881__6783(.A (b[3]), .B (a[3]), .Y (n_14));
  AND2X1 g5845__3680(.A (b[5]), .B (a[3]), .Y (n_13));
  AND2X1 g5873__1617(.A (b[1]), .B (a[3]), .Y (n_12));
  AND2X1 g5889__2802(.A (b[3]), .B (a[5]), .Y (n_11));
  AND2X1 g5857__1705(.A (b[7]), .B (a[3]), .Y (n_10));
  AND2X1 g5847__5122(.A (b[5]), .B (a[5]), .Y (n_9));
  AND2X1 g5852__8246(.A (b[1]), .B (a[5]), .Y (n_8));
  AND2X1 g5854__7098(.A (b[5]), .B (a[1]), .Y (n_7));
  AND2X1 g5859__6131(.A (b[3]), .B (a[7]), .Y (n_6));
  NAND2XL g5885__1881(.A (b[5]), .B (a[6]), .Y (n_27));
  NAND2XL g5867__5115(.A (b[5]), .B (a[4]), .Y (n_41));
  NAND2XL g5861__7482(.A (b[0]), .B (a[7]), .Y (n_24));
  NAND2XL g5879__4733(.A (b[1]), .B (a[6]), .Y (n_25));
  NAND2XL g5853__6161(.A (b[4]), .B (a[7]), .Y (n_26));
  NAND2XL g5844__9315(.A (b[2]), .B (a[7]), .Y (n_30));
  NAND2XL g5863__9945(.A (b[1]), .B (a[2]), .Y (n_21));
  NAND2XL g5848__2883(.A (b[4]), .B (a[3]), .Y (n_36));
  NAND2XL g5888__2346(.A (b[7]), .B (a[6]), .Y (n_35));
  NAND2XL g5876__1666(.A (b[7]), .B (a[2]), .Y (n_43));
  NAND2XL g5855__7410(.A (b[2]), .B (a[1]), .Y (n_44));
  NAND2XL g5856__6417(.A (b[3]), .B (a[2]), .Y (n_29));
  NAND2XL g5858__5477(.A (b[0]), .B (a[3]), .Y (n_20));
  NAND2XL g5883__2398(.A (b[1]), .B (a[4]), .Y (n_23));
  AND2X1 g5866__5107(.A (b[1]), .B (a[1]), .Y (n_5));
  AND2X1 g5869__6260(.A (b[7]), .B (a[5]), .Y (n_4));
  AND2X1 g5870__4319(.A (b[1]), .B (a[7]), .Y (n_3));
  AND2X1 g5875__8428(.A (b[5]), .B (a[7]), .Y (n_2));
  AND2X1 g5890__5526(.A (b[3]), .B (a[1]), .Y (n_1));
  AND2X1 g5877__6783(.A (b[7]), .B (a[1]), .Y (n_0));
  NAND2XL g5865__3680(.A (b[3]), .B (a[0]), .Y (n_45));
  NAND2XL g5872__1617(.A (b[4]), .B (a[1]), .Y (n_32));
  NAND2XL g5874__2802(.A (b[5]), .B (a[2]), .Y (n_37));
  NAND2XL g5860__1705(.A (b[6]), .B (a[7]), .Y (n_34));
  NAND2XL g5851__5122(.A (b[2]), .B (a[3]), .Y (n_28));
  NAND2XL g5880__8246(.A (b[5]), .B (a[0]), .Y (n_33));
  NAND2XL g5884__7098(.A (b[7]), .B (a[4]), .Y (n_47));
  NAND2XL g5887__6131(.A (b[4]), .B (a[5]), .Y (n_40));
  NAND2XL g5868__1881(.A (b[6]), .B (a[3]), .Y (n_42));
  NAND2XL g5862__5115(.A (b[7]), .B (a[0]), .Y (n_17));
  NAND2XL g5846__7482(.A (b[3]), .B (a[6]), .Y (n_31));
  NAND2XL g5878__4733(.A (b[0]), .B (a[1]), .Y (n_38));
  NAND2XL g5843__6161(.A (b[6]), .B (a[1]), .Y (n_16));
  NAND2XL g5864__9315(.A (b[0]), .B (a[5]), .Y (n_22));
  NAND2XL g5871__9945(.A (b[1]), .B (a[0]), .Y (n_39));
  NAND2XL g5849__2883(.A (b[3]), .B (a[4]), .Y (n_19));
  NAND2XL g5882__2346(.A (b[6]), .B (a[5]), .Y (n_46));
  NAND2XL g5850__1666(.A (b[2]), .B (a[5]), .Y (n_18));
endmodule

