
//input ports
add mapped point a[7] a[7] -type PI PI
add mapped point a[6] a[6] -type PI PI
add mapped point a[5] a[5] -type PI PI
add mapped point a[4] a[4] -type PI PI
add mapped point a[3] a[3] -type PI PI
add mapped point a[2] a[2] -type PI PI
add mapped point a[1] a[1] -type PI PI
add mapped point a[0] a[0] -type PI PI
add mapped point b[7] b[7] -type PI PI
add mapped point b[6] b[6] -type PI PI
add mapped point b[5] b[5] -type PI PI
add mapped point b[4] b[4] -type PI PI
add mapped point b[3] b[3] -type PI PI
add mapped point b[2] b[2] -type PI PI
add mapped point b[1] b[1] -type PI PI
add mapped point b[0] b[0] -type PI PI
add mapped point clk clk -type PI PI

//output ports
add mapped point result[15] result[15] -type PO PO
add mapped point result[14] result[14] -type PO PO
add mapped point result[13] result[13] -type PO PO
add mapped point result[12] result[12] -type PO PO
add mapped point result[11] result[11] -type PO PO
add mapped point result[10] result[10] -type PO PO
add mapped point result[9] result[9] -type PO PO
add mapped point result[8] result[8] -type PO PO
add mapped point result[7] result[7] -type PO PO
add mapped point result[6] result[6] -type PO PO
add mapped point result[5] result[5] -type PO PO
add mapped point result[4] result[4] -type PO PO
add mapped point result[3] result[3] -type PO PO
add mapped point result[2] result[2] -type PO PO
add mapped point result[1] result[1] -type PO PO
add mapped point result[0] result[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point op[15]/q op_reg[15]/Q -type DFF DFF
add mapped point op[14]/q op_reg[14]/Q -type DFF DFF
add mapped point A3/sum[7]/q A3_sum_reg[7]/Q -type DFF DFF
add mapped point A3/sum[6]/q A3_sum_reg[6]/Q -type DFF DFF
add mapped point op[13]/q op_reg[13]/Q -type DFF DFF
add mapped point A3/sum[5]/q A3_sum_reg[5]/Q -type DFF DFF
add mapped point op[12]/q op_reg[12]/Q -type DFF DFF
add mapped point A3/sum[4]/q A3_sum_reg[4]/Q -type DFF DFF
add mapped point op[11]/q op_reg[11]/Q -type DFF DFF
add mapped point A3/sum[3]/q A3_sum_reg[3]/Q -type DFF DFF
add mapped point op[10]/q op_reg[10]/Q -type DFF DFF
add mapped point A3/sum[2]/q A3_sum_reg[2]/Q -type DFF DFF
add mapped point op[9]/q op_reg[9]/Q -type DFF DFF
add mapped point A3/sum[1]/q A3_sum_reg[1]/Q -type DFF DFF
add mapped point A2/sum[8]/q A2_sum_reg[8]/Q -type DFF DFF
add mapped point A2/sum[9]/q A2_sum_reg[9]/Q -type DFF DFF
add mapped point op[8]/q op_reg[8]/Q -type DFF DFF
add mapped point A3/sum[0]/q A3_sum_reg[0]/Q -type DFF DFF
add mapped point A2/sum[7]/q A2_sum_reg[7]/Q -type DFF DFF
add mapped point A2/sum[6]/q A2_sum_reg[6]/Q -type DFF DFF
add mapped point A2/sum[5]/q A2_sum_reg[5]/Q -type DFF DFF
add mapped point A2/sum[4]/q A2_sum_reg[4]/Q -type DFF DFF
add mapped point op[7]/q op_reg[7]/Q -type DFF DFF
add mapped point A1/sum[7]/q A1_sum_reg[7]/Q -type DFF DFF
add mapped point A1/sum[8]/q A1_sum_reg[8]/Q -type DFF DFF
add mapped point A2/sum[3]/q A2_sum_reg[3]/Q -type DFF DFF
add mapped point op[6]/q op_reg[6]/Q -type DFF DFF
add mapped point A2/sum[2]/q A2_sum_reg[2]/Q -type DFF DFF
add mapped point A1/sum[6]/q A1_sum_reg[6]/Q -type DFF DFF
add mapped point op[5]/q op_reg[5]/Q -type DFF DFF
add mapped point A2/sum[1]/q A2_sum_reg[1]/Q -type DFF DFF
add mapped point A1/sum[5]/q A1_sum_reg[5]/Q -type DFF DFF
add mapped point M1/op[7]/q M1_op_reg[7]/Q -type DFF DFF
add mapped point M3/op[7]/q M3_op_reg[7]/Q -type DFF DFF
add mapped point M2/op[7]/q M2_op_reg[7]/Q -type DFF DFF
add mapped point M4/op[7]/q M4_op_reg[7]/Q -type DFF DFF
add mapped point M4/A3/sum[3]/q M4_A3_sum_reg[3]/Q -type DFF DFF
add mapped point M1/A3/sum[3]/q M1_A3_sum_reg[3]/Q -type DFF DFF
add mapped point M3/A3/sum[3]/q M3_A3_sum_reg[3]/Q -type DFF DFF
add mapped point M2/A3/sum[3]/q M2_A3_sum_reg[3]/Q -type DFF DFF
add mapped point M3/op[6]/q M3_op_reg[6]/Q -type DFF DFF
add mapped point M2/op[6]/q M2_op_reg[6]/Q -type DFF DFF
add mapped point M1/op[6]/q M1_op_reg[6]/Q -type DFF DFF
add mapped point M4/op[6]/q M4_op_reg[6]/Q -type DFF DFF
add mapped point M3/A3/sum[2]/q M3_A3_sum_reg[2]/Q -type DFF DFF
add mapped point M1/A3/sum[2]/q M1_A3_sum_reg[2]/Q -type DFF DFF
add mapped point M4/A3/sum[2]/q M4_A3_sum_reg[2]/Q -type DFF DFF
add mapped point M2/A3/sum[2]/q M2_A3_sum_reg[2]/Q -type DFF DFF
add mapped point A1/sum[4]/q A1_sum_reg[4]/Q -type DFF DFF
add mapped point op[4]/q op_reg[4]/Q -type DFF DFF
add mapped point M1/op[5]/q M1_op_reg[5]/Q -type DFF DFF
add mapped point M3/op[5]/q M3_op_reg[5]/Q -type DFF DFF
add mapped point M4/op[5]/q M4_op_reg[5]/Q -type DFF DFF
add mapped point M2/op[5]/q M2_op_reg[5]/Q -type DFF DFF
add mapped point A2/sum[0]/q A2_sum_reg[0]/Q -type DFF DFF
add mapped point M4/A3/sum[1]/q M4_A3_sum_reg[1]/Q -type DFF DFF
add mapped point M1/A3/sum[1]/q M1_A3_sum_reg[1]/Q -type DFF DFF
add mapped point M3/A3/sum[1]/q M3_A3_sum_reg[1]/Q -type DFF DFF
add mapped point M2/A3/sum[1]/q M2_A3_sum_reg[1]/Q -type DFF DFF
add mapped point M3/A2/sum[4]/q M3_A2_sum_reg[4]/Q -type DFF DFF
add mapped point M1/A2/sum[4]/q M1_A2_sum_reg[4]/Q -type DFF DFF
add mapped point M1/A2/sum[5]/q M1_A2_sum_reg[5]/Q -type DFF DFF
add mapped point M3/A2/sum[5]/q M3_A2_sum_reg[5]/Q -type DFF DFF
add mapped point M2/A2/sum[4]/q M2_A2_sum_reg[4]/Q -type DFF DFF
add mapped point M4/A2/sum[4]/q M4_A2_sum_reg[4]/Q -type DFF DFF
add mapped point M2/A2/sum[5]/q M2_A2_sum_reg[5]/Q -type DFF DFF
add mapped point M4/A2/sum[5]/q M4_A2_sum_reg[5]/Q -type DFF DFF
add mapped point M3/op[4]/q M3_op_reg[4]/Q -type DFF DFF
add mapped point M2/op[4]/q M2_op_reg[4]/Q -type DFF DFF
add mapped point M4/op[4]/q M4_op_reg[4]/Q -type DFF DFF
add mapped point M1/op[4]/q M1_op_reg[4]/Q -type DFF DFF
add mapped point M3/A2/sum[3]/q M3_A2_sum_reg[3]/Q -type DFF DFF
add mapped point M1/A2/sum[3]/q M1_A2_sum_reg[3]/Q -type DFF DFF
add mapped point M4/A2/sum[3]/q M4_A2_sum_reg[3]/Q -type DFF DFF
add mapped point M2/A2/sum[3]/q M2_A2_sum_reg[3]/Q -type DFF DFF
add mapped point M3/A3/sum[0]/q M3_A3_sum_reg[0]/Q -type DFF DFF
add mapped point M1/A3/sum[0]/q M1_A3_sum_reg[0]/Q -type DFF DFF
add mapped point M4/A3/sum[0]/q M4_A3_sum_reg[0]/Q -type DFF DFF
add mapped point M2/A3/sum[0]/q M2_A3_sum_reg[0]/Q -type DFF DFF
add mapped point A1/sum[3]/q A1_sum_reg[3]/Q -type DFF DFF
add mapped point A1/sum[2]/q A1_sum_reg[2]/Q -type DFF DFF
add mapped point M1/A1/sum[4]/q M1_A1_sum_reg[4]/Q -type DFF DFF
add mapped point M1/A1/sum[3]/q M1_A1_sum_reg[3]/Q -type DFF DFF
add mapped point M3/A2/sum[2]/q M3_A2_sum_reg[2]/Q -type DFF DFF
add mapped point M2/A2/sum[2]/q M2_A2_sum_reg[2]/Q -type DFF DFF
add mapped point M1/A2/sum[2]/q M1_A2_sum_reg[2]/Q -type DFF DFF
add mapped point M4/A2/sum[2]/q M4_A2_sum_reg[2]/Q -type DFF DFF
add mapped point M2/A1/sum[4]/q M2_A1_sum_reg[4]/Q -type DFF DFF
add mapped point M3/A1/sum[3]/q M3_A1_sum_reg[3]/Q -type DFF DFF
add mapped point M4/A1/sum[3]/q M4_A1_sum_reg[3]/Q -type DFF DFF
add mapped point M4/A1/sum[4]/q M4_A1_sum_reg[4]/Q -type DFF DFF
add mapped point M2/A1/sum[3]/q M2_A1_sum_reg[3]/Q -type DFF DFF
add mapped point M3/A1/sum[4]/q M3_A1_sum_reg[4]/Q -type DFF DFF
add mapped point op[3]/q op_reg[3]/Q -type DFF DFF
add mapped point M1/op[3]/q M1_op_reg[3]/Q -type DFF DFF
add mapped point M4/op[3]/q M4_op_reg[3]/Q -type DFF DFF
add mapped point M3/op[3]/q M3_op_reg[3]/Q -type DFF DFF
add mapped point M2/op[3]/q M2_op_reg[3]/Q -type DFF DFF
add mapped point M1/A2/sum[1]/q M1_A2_sum_reg[1]/Q -type DFF DFF
add mapped point M3/A2/sum[1]/q M3_A2_sum_reg[1]/Q -type DFF DFF
add mapped point M4/A2/sum[1]/q M4_A2_sum_reg[1]/Q -type DFF DFF
add mapped point M2/A2/sum[1]/q M2_A2_sum_reg[1]/Q -type DFF DFF
add mapped point M1/A1/sum[2]/q M1_A1_sum_reg[2]/Q -type DFF DFF
add mapped point op[2]/q op_reg[2]/Q -type DFF DFF
add mapped point M4/A1/sum[2]/q M4_A1_sum_reg[2]/Q -type DFF DFF
add mapped point M2/A1/sum[2]/q M2_A1_sum_reg[2]/Q -type DFF DFF
add mapped point M3/A1/sum[2]/q M3_A1_sum_reg[2]/Q -type DFF DFF
add mapped point M1/op[2]/q M1_op_reg[2]/Q -type DFF DFF
add mapped point A1/sum[1]/q A1_sum_reg[1]/Q -type DFF DFF
add mapped point M4/op[2]/q M4_op_reg[2]/Q -type DFF DFF
add mapped point M3/op[2]/q M3_op_reg[2]/Q -type DFF DFF
add mapped point M2/op[2]/q M2_op_reg[2]/Q -type DFF DFF
add mapped point M2/A2/sum[0]/q M2_A2_sum_reg[0]/Q -type DFF DFF
add mapped point M1/A2/sum[0]/q M1_A2_sum_reg[0]/Q -type DFF DFF
add mapped point M4/A2/sum[0]/q M4_A2_sum_reg[0]/Q -type DFF DFF
add mapped point M3/A2/sum[0]/q M3_A2_sum_reg[0]/Q -type DFF DFF
add mapped point M1/A1/sum[1]/q M1_A1_sum_reg[1]/Q -type DFF DFF
add mapped point M2/A1/sum[1]/q M2_A1_sum_reg[1]/Q -type DFF DFF
add mapped point M3/A1/sum[1]/q M3_A1_sum_reg[1]/Q -type DFF DFF
add mapped point M4/A1/sum[1]/q M4_A1_sum_reg[1]/Q -type DFF DFF
add mapped point M1/V3/H1/sum/q M1_V3_H1_sum_reg/Q -type DFF DFF
add mapped point M1/V2/H1/sum/q M1_V2_H1_sum_reg/Q -type DFF DFF
add mapped point M1/V3/H1/carry/q M1_V3_H1_carry_reg/Q -type DFF DFF
add mapped point M1/V2/H1/carry/q M1_V2_H1_carry_reg/Q -type DFF DFF
add mapped point M2/V3/H1/sum/q M2_V3_H1_sum_reg/Q -type DFF DFF
add mapped point M3/V2/H1/carry/q M3_V2_H1_carry_reg/Q -type DFF DFF
add mapped point M2/V2/H1/carry/q M2_V2_H1_carry_reg/Q -type DFF DFF
add mapped point M4/V3/H1/carry/q M4_V3_H1_carry_reg/Q -type DFF DFF
add mapped point M3/V4/H1/sum/q M3_V4_H1_sum_reg/Q -type DFF DFF
add mapped point op[1]/q op_reg[1]/Q -type DFF DFF
add mapped point M4/V2/H1/sum/q M4_V2_H1_sum_reg/Q -type DFF DFF
add mapped point M4/V4/H1/sum/q M4_V4_H1_sum_reg/Q -type DFF DFF
add mapped point M1/V4/H1/carry/q M1_V4_H1_carry_reg/Q -type DFF DFF
add mapped point M4/V4/H1/carry/q M4_V4_H1_carry_reg/Q -type DFF DFF
add mapped point M3/V4/H1/carry/q M3_V4_H1_carry_reg/Q -type DFF DFF
add mapped point M4/V1/H1/sum/q M4_V1_H1_sum_reg/Q -type DFF DFF
add mapped point M1/V1/H1/sum/q M1_V1_H1_sum_reg/Q -type DFF DFF
add mapped point M2/V1/H1/carry/q M2_V1_H1_carry_reg/Q -type DFF DFF
add mapped point M3/V2/H1/sum/q M3_V2_H1_sum_reg/Q -type DFF DFF
add mapped point M3/V3/H1/sum/q M3_V3_H1_sum_reg/Q -type DFF DFF
add mapped point M3/V3/H1/carry/q M3_V3_H1_carry_reg/Q -type DFF DFF
add mapped point M2/V4/H1/sum/q M2_V4_H1_sum_reg/Q -type DFF DFF
add mapped point M1/V1/H1/carry/q M1_V1_H1_carry_reg/Q -type DFF DFF
add mapped point M4/V2/H1/carry/q M4_V2_H1_carry_reg/Q -type DFF DFF
add mapped point M3/V1/H1/carry/q M3_V1_H1_carry_reg/Q -type DFF DFF
add mapped point M2/V3/H1/carry/q M2_V3_H1_carry_reg/Q -type DFF DFF
add mapped point M2/V2/H1/sum/q M2_V2_H1_sum_reg/Q -type DFF DFF
add mapped point M4/V3/H1/sum/q M4_V3_H1_sum_reg/Q -type DFF DFF
add mapped point M1/V4/H1/sum/q M1_V4_H1_sum_reg/Q -type DFF DFF
add mapped point M4/V1/H1/carry/q M4_V1_H1_carry_reg/Q -type DFF DFF
add mapped point M2/V1/H1/sum/q M2_V1_H1_sum_reg/Q -type DFF DFF
add mapped point M3/V1/H1/sum/q M3_V1_H1_sum_reg/Q -type DFF DFF
add mapped point M2/V4/H1/carry/q M2_V4_H1_carry_reg/Q -type DFF DFF
add mapped point A1/sum[0]/q A1_sum_reg[0]/Q -type DFF DFF
add mapped point M2/op[1]/q M2_op_reg[1]/Q -type DFF DFF
add mapped point M4/op[1]/q M4_op_reg[1]/Q -type DFF DFF
add mapped point M1/op[1]/q M1_op_reg[1]/Q -type DFF DFF
add mapped point M3/op[1]/q M3_op_reg[1]/Q -type DFF DFF
add mapped point M3/A1/sum[0]/q M3_A1_sum_reg[0]/Q -type DFF DFF
add mapped point M2/A1/sum[0]/q M2_A1_sum_reg[0]/Q -type DFF DFF
add mapped point M1/A1/sum[0]/q M1_A1_sum_reg[0]/Q -type DFF DFF
add mapped point M4/A1/sum[0]/q M4_A1_sum_reg[0]/Q -type DFF DFF
add mapped point M1/V4/H0/sum/q M1_V4_H0_sum_reg/Q -type DFF DFF
add mapped point M2/V4/H0/sum/q M2_V4_H0_sum_reg/Q -type DFF DFF
add mapped point M3/V3/H0/sum/q M3_V3_H0_sum_reg/Q -type DFF DFF
add mapped point M3/V2/H0/sum/q M3_V2_H0_sum_reg/Q -type DFF DFF
add mapped point M3/V1/H0/sum/q M3_V1_H0_sum_reg/Q -type DFF DFF
add mapped point M4/V1/H0/sum/q M4_V1_H0_sum_reg/Q -type DFF DFF
add mapped point M2/V1/H0/sum/q M2_V1_H0_sum_reg/Q -type DFF DFF
add mapped point M3/V4/H0/sum/q M3_V4_H0_sum_reg/Q -type DFF DFF
add mapped point M1/V3/H0/sum/q M1_V3_H0_sum_reg/Q -type DFF DFF
add mapped point M4/V2/H0/sum/q M4_V2_H0_sum_reg/Q -type DFF DFF
add mapped point M2/V3/H0/sum/q M2_V3_H0_sum_reg/Q -type DFF DFF
add mapped point M2/V2/H0/sum/q M2_V2_H0_sum_reg/Q -type DFF DFF
add mapped point M4/V3/H0/sum/q M4_V3_H0_sum_reg/Q -type DFF DFF
add mapped point M4/V4/H0/sum/q M4_V4_H0_sum_reg/Q -type DFF DFF
add mapped point M1/V2/H0/sum/q M1_V2_H0_sum_reg/Q -type DFF DFF
add mapped point M1/V1/H0/sum/q M1_V1_H0_sum_reg/Q -type DFF DFF
add mapped point op[0]/q op_reg[0]/Q -type DFF DFF
add mapped point M3/V4/H0/carry/q M3_V4_H0_carry_reg/Q -type DFF DFF
add mapped point M3/V1/H0/carry/q M3_V1_H0_carry_reg/Q -type DFF DFF
add mapped point M4/V2/H0/carry/q M4_V2_H0_carry_reg/Q -type DFF DFF
add mapped point M1/V4/H0/carry/q M1_V4_H0_carry_reg/Q -type DFF DFF
add mapped point M1/V1/H0/carry/q M1_V1_H0_carry_reg/Q -type DFF DFF
add mapped point M2/V3/H0/carry/q M2_V3_H0_carry_reg/Q -type DFF DFF
add mapped point M2/V2/H0/carry/q M2_V2_H0_carry_reg/Q -type DFF DFF
add mapped point M4/V1/H0/carry/q M4_V1_H0_carry_reg/Q -type DFF DFF
add mapped point M1/V2/H0/carry/q M1_V2_H0_carry_reg/Q -type DFF DFF
add mapped point M4/V3/H0/carry/q M4_V3_H0_carry_reg/Q -type DFF DFF
add mapped point M4/V4/H0/carry/q M4_V4_H0_carry_reg/Q -type DFF DFF
add mapped point M1/V3/H0/carry/q M1_V3_H0_carry_reg/Q -type DFF DFF
add mapped point M3/V3/H0/carry/q M3_V3_H0_carry_reg/Q -type DFF DFF
add mapped point M3/V2/H0/carry/q M3_V2_H0_carry_reg/Q -type DFF DFF
add mapped point M2/V1/H0/carry/q M2_V1_H0_carry_reg/Q -type DFF DFF
add mapped point M2/V4/H0/carry/q M2_V4_H0_carry_reg/Q -type DFF DFF
add mapped point M1/op[0]/q M1_op_reg[0]/Q -type DFF DFF
add mapped point M3/op[0]/q M3_op_reg[0]/Q -type DFF DFF
add mapped point M2/op[0]/q M2_op_reg[0]/Q -type DFF DFF
add mapped point M4/op[0]/q M4_op_reg[0]/Q -type DFF DFF
add mapped point M1/V1/res/q M1_V1_res_reg/Q -type DFF DFF
add mapped point M3/V1/res/q M3_V1_res_reg/Q -type DFF DFF
add mapped point M1/V4/res/q M1_V4_res_reg/Q -type DFF DFF
add mapped point M4/V3/res/q M4_V3_res_reg/Q -type DFF DFF
add mapped point M2/V3/res/q M2_V3_res_reg/Q -type DFF DFF
add mapped point M1/V2/res/q M1_V2_res_reg/Q -type DFF DFF
add mapped point M3/V3/res/q M3_V3_res_reg/Q -type DFF DFF
add mapped point M3/V4/res/q M3_V4_res_reg/Q -type DFF DFF
add mapped point M2/V1/res/q M2_V1_res_reg/Q -type DFF DFF
add mapped point M4/V1/res/q M4_V1_res_reg/Q -type DFF DFF
add mapped point M4/V4/res/q M4_V4_res_reg/Q -type DFF DFF
add mapped point M2/V2/res/q M2_V2_res_reg/Q -type DFF DFF
add mapped point M2/V4/res/q M2_V4_res_reg/Q -type DFF DFF
add mapped point M4/V2/res/q M4_V2_res_reg/Q -type DFF DFF
add mapped point M3/V2/res/q M3_V2_res_reg/Q -type DFF DFF
add mapped point M1/V3/res/q M1_V3_res_reg/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
